services:
  sql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql-server
    restart: always
    environment:
      MSSQL_SA_PASSWORD: Password01
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 30s
      retries: 5
      timeout: 10s

  rabbitmq:
    build: ./rabbitmq/
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - app-network
    healthcheck:
       test: ["CMD", "curl", "-u", "admin:admin123", "-f", "http://localhost:15672/api/healthchecks/node"]
       interval: 30s
       retries: 5
       timeout: 10s

  mapi-service:
    build: ./Technosavvy.mAPI/
    container_name: mapi-service
    depends_on:
        sql-server:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
    restart: always
    ports:
      - "5007:5007"
    networks:
      - app-network

  watcher-service:
    build: ./Technosavvy.watcher/
    container_name: watcher-service
      #  depends_on:
      # rabbitmq:
      #   condition: service_healthy
    restart: always
    ports:
      - "5014:5014"
    networks:
      - app-network

  webui-service:
    build: ./Technosavvy.webui/
    container_name: webui-service
    depends_on:
      - mapi-service
    restart: always
    ports:
      - "5003:5003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

