name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  deploy:
    runs-on: self-hosted  # Specify that this job runs on your self-hosted agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k .